### ISSUE TITLE
Add GitHub Actions workflow for automatic npm publishing

### ISSUE THREAD

**Issue by xiaotiantakumi** [xiaotiantakumi/WebLinkCollector#14]
## Feature Request
Implement a GitHub Actions workflow that automatically publishes the package to npm when changes are merged to the main branch.

## Current Situation
Currently, publishing to npm requires manual steps after merging to the main branch, which can be error-prone and time-consuming.

## Proposed Solution
Create a GitHub Actions workflow with the following characteristics:

1. **Trigger**: The workflow should be triggered when changes are merged to the main branch
2. **Authentication**: Set up npm authentication using GitHub Secrets
3. **Build & Publish Process**:
   - Install dependencies
   - Run tests to ensure everything is working
   - Build the package
   - Publish to npm registry

## Implementation Details

The workflow file could be placed at `.github/workflows/npm-publish.yml` with contents similar to:

```yaml
name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
```

## Requirements
- Create an NPM_TOKEN in npm and add it to GitHub repository secrets
- Ensure package.json is properly configured for publishing
- Consider implementing version bumping strategy (manual or automatic)

## Benefits
- Ensures consistent releases
- Reduces manual effort
- Minimizes human error
- Improves release cycle speed
