### ISSUE TITLE
Set up GitHub Actions for automated testing on Pull Requests

### ISSUE THREAD

**Issue by xiaotiantakumi** [xiaotiantakumi/WebLinkCollector#15]
## Feature Request
Implement a GitHub Actions workflow that automatically runs tests whenever a Pull Request is created or updated.

## Current Situation
Currently, tests need to be run manually before merging PRs, which can lead to:
- Potential oversight of test failures
- Inconsistent test environments between developers
- Additional manual steps in the development workflow

## Proposed Solution
Create a GitHub Actions workflow with the following characteristics:

1. **Trigger**: The workflow should be triggered when:
   - A new PR is opened
   - An existing PR is updated with new commits
   - A PR is reopened

2. **Test Process**:
   - Install dependencies
   - Run linting checks
   - Run the test suite 
   - Report test coverage
   - Fail the check if tests fail or if coverage drops below the threshold (91%)

## Implementation Details

The workflow file could be placed at `.github/workflows/pr-test.yml` with contents similar to:

```yaml
name: PR Tests

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Check test coverage
        run: |
          COVERAGE=$(npm test -- --coverage | grep "All files" | awk '{print $4}' | sed 's/%//')
          if (( $(echo "$COVERAGE < 91" | bc -l) )); then
            echo "Test coverage is below 91%: $COVERAGE%"
            exit 1
          fi
```

## Benefits
- Ensures code quality on all PRs
- Creates consistent testing environments
- Provides immediate feedback to developers
- Prevents merging code that doesn't pass tests
- Maintains the required test coverage
- Makes test results visible to all team members and reviewers

## Additional Considerations
- Consider adding status badges to the README
- Add comments to the PR with test results
- Consider caching dependencies to speed up workflows
- Consider running tests on different Node.js versions
